-- SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
-- FROM REST_INFO R,
--     (
--         SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
--         FROM REST_INFO 
--         GROUP BY FOOD_TYPE
--     ) BEST
-- WHERE R.FOOD_TYPE = BEST.FOOD_TYPE
-- AND R.FAVORITES = BEST.FAVORITES
-- ORDER BY FOOD_TYPE DESC
-- ;

-- 좀 더 효율적인 코드..
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT A.*
        , ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
    FROM REST_INFO A
    ) X
WHERE X.RN = 1
ORDER BY FOOD_TYPE DESC
;