SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R,
    (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
        FROM REST_INFO 
        GROUP BY FOOD_TYPE
    ) BEST
WHERE R.FOOD_TYPE = BEST.FOOD_TYPE
AND R.FAVORITES = BEST.FAVORITES
ORDER BY FOOD_TYPE DESC
;