SELECT *
FROM 
    (SELECT DISTINCT A.CAR_ID
        , A.CAR_TYPE
        , (A.DAILY_FEE * ((100-C.DISCOUNT_RATE)/100) * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    , CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    , CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    WHERE A.CAR_TYPE IN ('세단', 'SUV')
    AND A.CAR_ID = B.CAR_ID
    AND A.CAR_TYPE = C.CAR_TYPE
    AND C.DURATION_TYPE = '30일 이상'
    AND B.CAR_ID NOT IN (
      SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_DATE('20221101', 'YYYYMMDD') BETWEEN START_DATE AND END_DATE
        OR TO_DATE('20221130', 'YYYYMMDD') BETWEEN START_DATE AND END_DATE
    )
    ) X
WHERE X.FEE BETWEEN 500000 AND 1999999
ORDER BY X.FEE DESC, X.CAR_TYPE, X.CAR_ID
;