SELECT X.*
FROM (
    SELECT CAR_ID, ROUND(AVG(END_DATE-START_DATE+1),1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    ) X
WHERE X.AVERAGE_DURATION >= 7.0
ORDER BY X.AVERAGE_DURATION DESC, X.CAR_ID DESC
;