SELECT A.USER_ID, A.NICKNAME, B.PRICE AS TOTAL_SALES
FROM USED_GOODS_USER A,
    (
        SELECT WRITER_ID, SUM(PRICE) AS PRICE
        FROM USED_GOODS_BOARD 
        WHERE STATUS = 'DONE'
        GROUP BY WRITER_ID
    ) B
WHERE A.USER_ID = B.WRITER_ID
AND B.PRICE >= 700000
ORDER BY B.PRICE
;

