SELECT TO_CHAR(B.SALES_DATE, 'YYYY') AS YEAR
        , TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM')) AS MONTH
        , COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS
        , ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE B
WHERE B.USER_ID IN (
    SELECT A.USER_ID
    FROM USER_INFO A
    WHERE TO_CHAR(A.JOINED, 'YYYY') = '2021'
)
GROUP BY TO_CHAR(B.SALES_DATE, 'YYYY'), TO_CHAR(B.SALES_DATE, 'MM')
ORDER BY TO_CHAR(B.SALES_DATE, 'YYYY'), TO_CHAR(B.SALES_DATE, 'MM')
;