-- SELECT A.AUTHOR_ID
--     , (SELECT AUTHOR_NAME FROM AUTHOR WHERE AUTHOR_ID = A.AUTHOR_ID) AS AUTHOR_NAME
--     , A.CATEGORY
-- FROM BOOK A,
--     (
--         SELECT BOOK_ID, SUM(SALES) AS TOTAL
--         FROM BOOK_SALES
--         WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
--         GROUP BY BOOK_ID
--     ) B
-- WHERE A.BOOK_ID = B.BOOK_ID
-- GROUP BY A.AUTHOR_ID, A.CATEGORY
-- ORDER BY A.AUTHOR_ID, A.CATEGORY DESC
-- ;

SELECT A.AUTHOR_ID
    , (SELECT AUTHOR_NAME FROM AUTHOR WHERE AUTHOR_ID = A.AUTHOR_ID) AS AUTHOR_NAME
    , A.CATEGORY
    , SUM(A.PRICE * B.SALES) AS TOTAL_SALES
FROM BOOK A, BOOK_SALES B, AUTHOR C
WHERE A.BOOK_ID = B.BOOK_ID
AND A.AUTHOR_ID = C.AUTHOR_ID
AND TO_CHAR(B.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC
;