SELECT X.PRODUCT_ID
    , X.PRODUCT_NAME
    , (X.PRICE * Y.AMT) AS TOTAL_SALES
FROM FOOD_PRODUCT X, (
    SELECT A.PRODUCT_ID, SUM(A.AMOUNT) AS AMT
    FROM FOOD_ORDER A
    WHERE TO_CHAR(A.PRODUCE_DATE, 'YYYYMM') = '202205'
    GROUP BY A.PRODUCT_ID
) Y
WHERE X.PRODUCT_ID = Y.PRODUCT_ID
ORDER BY 3 DESC, 1
;