-- 코드를 입력하세요
SELECT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A, 
    (
        SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT
        FROM ONLINE_SALE
        GROUP BY USER_ID, PRODUCT_ID
    ) B
WHERE A.USER_ID = B.USER_ID
AND A.PRODUCT_ID = B.PRODUCT_ID
AND B.CNT >= 2
GROUP BY A.USER_ID, A.PRODUCT_ID
ORDER BY A.USER_ID, A.PRODUCT_ID DESC
;