-- 코드를 입력하세요
SELECT B.PRODUCT_CODE
, A.AMT * B.PRICE AS SALES
FROM (
    SELECT A.PRODUCT_ID
        , SUM(SALES_AMOUNT) AS AMT
    FROM PRODUCT A, OFFLINE_SALE  B
    WHERE A.PRODUCT_ID = B.PRODUCT_ID
    GROUP BY A.PRODUCT_ID
    ) A
    , PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, B.PRODUCT_CODE
;
