-- SELECT (SELECT MEMBER_NAME FROM MEMBER_PROFILE WHERE MEMBER_ID = B.MEMBER_ID) AS MEMBER_NAME
--     , A.REVIEW_TEXT
--     , TO_CHAR(A.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
-- FROM REST_REVIEW A,
--     (
--         SELECT MEMBER_ID, COUNT(*) AS CNT
--         FROM REST_REVIEW
--         GROUP BY MEMBER_ID
--         ORDER BY CNT DESC
--     ) B
-- WHERE B.ROWNUM = 1
-- AND A.MEMBER_ID = B.MEMBER_ID
-- ORDER BY 3,2
-- ;

SELECT (SELECT MEMBER_NAME FROM MEMBER_PROFILE WHERE MEMBER_ID = X.MEMBER_ID) AS MEMBER_NAME
    , Y.REVIEW_TEXT
    , TO_CHAR(Y.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM (
    SELECT MEMBER_ID, RANK() OVER(ORDER BY CNT DESC) AS RNK
    FROM  (
            SELECT MEMBER_ID, COUNT(*) CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        )
    ) X
    , REST_REVIEW Y
WHERE X.RNK = 1
AND X.MEMBER_ID = Y.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
;