SELECT (SELECT MEMBER_NAME FROM MEMBER_PROFILE WHERE MEMBER_ID = X.MEMBER_ID) AS MEMBER_NAME
    , Y.REVIEW_TEXT
    , TO_CHAR(Y.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM (
    SELECT MEMBER_ID, RANK() OVER(ORDER BY CNT DESC) AS RANK
    FROM  (
            SELECT MEMBER_ID, COUNT(*) CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        )
    ) X
    , REST_REVIEW Y
WHERE X.RANK = 1
AND X.MEMBER_ID = Y.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
;