-- 코드를 입력하세요
-- SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, X.SCORE
-- FROM REST_INFO RI,
--     (
--         SELECT RR.REST_ID, ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
--         FROM REST_INFO RI, REST_REVIEW RR
--         WHERE RI.ADDRESS LIKE '서울특별시%'
--         AND RI.REST_ID = RR.REST_ID
--         GROUP BY RR.REST_ID
--     ) X
-- WHERE RI.REST_ID = X.REST_ID
-- ORDER BY NVL(X.SCORE, 0) DESC, RI.FAVORITES DESC
-- ;

SELECT 
    X.REST_ID
    , RI.REST_NAME
    , RI.FOOD_TYPE
    , RI.FAVORITES
    , RI.ADDRESS
    , ROUND(X.SCORE,2) AS SCORE
FROM (
        SELECT RI.REST_ID AS REST_ID, AVG(RR.REVIEW_SCORE) AS SCORE
        FROM REST_INFO RI,
            REST_REVIEW RR
        WHERE RI.REST_ID = RR.REST_ID
        AND RI.ADDRESS LIKE '서울%'
        GROUP BY RI.REST_ID
    ) X
    , REST_INFO RI
WHERE X.REST_ID = RI.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC
;